### ISSUE TITLE
[1.18.1] Compat issue with Quark

### ISSUE THREAD

**Issue by Eario** [JoeFoxe/Hexerei-1.18#19]
Loading this mod alongside Quark causes a crash to desktop.
Forge version: 39.0.75
Mod versions: Hexerei 0.1.14, Quark 3.0-334

Log:
[2022-02-11-6.log](https://github.com/JoeFoxe/Hexerei-1.18/files/8049379/2022-02-11-6.log)

**Comment by IXaar1** [comment]
As for me, i can not replicate it. Everything seems working to me fine. Could be another mod issue.

**Comment by FreshAlacrity** [comment]
I've had Forge 39.0.66, Hexerei 0.1.14, and Quark 3.0-334 loading in reliably for me; just updated to Forge 39.0.75 to double-check this issue in particular and that also loaded in without a hitch; so did Forge 39.0.76 with Hexerei 0.1.14 and Quark 3.0-334 and then also Forge 39.0.76 with Hexerei 0.1.14 and Quark 3.1-336 (the most recent release)

As a side note in it helps anyone, all of those tests were also in a pack with 60+ other mods, including Quark Oddities, Create 0.4d, Flywheel 0.6.0 (tested on most recent versions with both backend off and in instancing mode and an active contraption), and even Optifine HD_U_H4 with ComplementaryShaders 4.3.3; no compatibility issues that I could see.

I have found that sometimes creating a fresh profile can fix things when nothing else does, that might be something to try? To double-check compatibility issues especially I like to start a fresh profile with only those mods, just to make sure that's what's going on, but since I'm not having the same issue with a bunch of other mods I think it's probably some other sort of conflict or interaction happening here. 😅
