### ISSUE TITLE
[Suggestion\Feature Request] Crafttweaker or KubeJS compatibility with mixing cauldron and dipper

### ISSUE THREAD

**Issue by lerokko** [JoeFoxe/Hexerei-1.18#21]
Crafttweaker or KubeJS compatibility (or recipe removal/addition via datapacks) for the mixing cauldron and dipper so mod pack makers can make their own recipes with it.

**Comment by FreshAlacrity** [comment]
You can add your own mixing cauldron, dipper, and pestle and mortar recipes with datapacks in the current version. Just copy the JSON recipe files for the appropriate recipe type from the Hexerei repo or .jar to your datapack's recipes folder and modify to suit your needs. :)

I haven't tried CraftTweaker or KubeJS yet but iirc adding compatibility for those is more somebody who knows that system making a plugin or addon for that to support the Hexerei JSON format?

**Comment by Mrthomas20121** [comment]
both crafttweaker and KubeJS technically support mods that don't have compat, you're basically writting the JSON in Zenscript/Javascript respectively, it's alright but not as a good as full compat(at least for crafttweaker).
i might look into doing crafttweaker compat(i need to figure out if things changed since 1.16 crafttweaker)
