### ISSUE TITLE
Unblock Hexerei for third-party launchers

### ISSUE THREAD

**Issue by ExistingExpert** [JoeFoxe/Hexerei-1.18#38]
May I ask why this mod was blocked for third-party launchers? I can only assume it was so that CF's download statistics are not messed up. Can this mod be unblocked? Many people don't, or straight up **can't** use Overwolf's launcher due to privacy concerns, and the fact that it is not available for linux (it only supports WOW). Due to this people have to manually download this mod everytime from the website (which, imo, is pretty meh) and forgo automatic updates for good.
![image](https://user-images.githubusercontent.com/71560815/174950644-a873d379-42ac-4935-a3c0-d0102dde5638.png)

**Comment by DDriggs00** [comment]
Second this. It is a pretty severe QoL issue for anyone not willing to subject their computer to Overwolf's spyware, as well as those using Linux.

**Comment by copygirl** [comment]
I had also addressed this in #35 before.
Going to remove the mod from my modpack for now.

**Comment by JoeFoxe** [comment]
> Second this. It is a pretty severe QoL issue for anyone not willing to subject their computer to Overwolf's spyware, as well as those using Linux.

honestly this is very not QoL for me, as im not here for free labor. im not spending each and every day working tirelessly on this to get absolutely nothing in return. I cant live off that. I need to actually survive to be able to produce this mod. So again and for the last time, as I have even added to stop asking about  this on my curseforge page, that I am not going to change my distribution settings unless im properly funded. and its not like oh here is $20 thanks for your extremely hard work that you do, go buy food one time, while everyone can endlessly play your mod for free anywhere and then get back to work on the next updates

**Comment by JoeFoxe** [comment]
also any of the mods can be downloaded on curseforge can placed into your third party launchers, which allows the developers to get ad revenue.  I highly suggest doing that instead of blatantly taking the mods from scummy third party applications which  dont pay developers anything

**Comment by copygirl** [comment]
> ... taking the mods from scummy third party applications which dont pay developers anything

Keep in mind the CurseForge launcher itself is technically a third-party application. The only official launcher is Mojang's.

Third party launchers like MultiMC and PolyMC (the ones I'm familiar with) and tools like packwiz are anything but scummy. They're written by concerned developers, modders and players, which are just as interested in supporting mod developers and other content creators just like anyone else. Probably even more than the average CurseForge user. And they actually care about improving their software rather than being swayed by profit. As we all know CF has been lagging behind in the usability department.

Certain tools also allow for workflows simply not possible using the CF launcher. And you already know about Linux users having to bite the dust. Modded Minecraft runs flawlessly on Linux.

These tools are arguably less scummy because they do not rely on collecting and using user data to potentially sell, or show unwanted, potentially dangerous ads. And the ad platforms themselves likely collect and sell data themselves.

Due to the nature of these open source tools that do not want to compromise the users' privacy and overall user experience, it is not straight-forward to implement a monetization system that could reward creators. It's also non-trivial to support such a system and make it robust against abuse in the future. And when it comes to CurseForge specifically, the [terms and conditions](https://support.curseforge.com/en/support/solutions/articles/9000207405-curse-forge-3rd-party-api-terms-and-conditions) to gain an API key that allows access to restricted mods like yours, are difficult to impossible to follow for open source projects. For example, the API key could not be made accessible in the repository, breaking reproducible builds.

[Modrinth](https://modrinth.com/) is an alternative, open hosting platform which will be working on a reward system as one of its goals. Please at least consider it as an option when it eventually does this.

Lastly, I don't think you'll be hurt by enabling third-party downloads. As you know, anyone can go to your mod's CurseForge page, download the mod, and just include the `.jar` file in a modpack, or even reupload it elsewhere. It's also possible for tools to avoid the API and just scrape the website and act like a web browser downloading the mod. It is not protection against scummy behavior. Meanwhile, when you enable third-party downloads, it allows legitimate tools to download the mod through the official CurseForge API, increasing the mod's popularity and download count on the website.

On the contrary, if you disable third-party access, you lose out on a potential user base, which can affect your mod's overall popularity both on CurseForge's website and elsewhere on the internet, which will in turn decrease the number of first-party downloads and reward points you'll get in the end.

> any of the mods can be downloaded on curseforge can placed into your third party launchers, which allows the developers to get ad revenue

This works for users putting together their own personal set of mods. Not for modpack developers.
