### ISSUE TITLE
allow third-party launchers

### ISSUE THREAD

**Issue by lele92007** [JoeFoxe/Hexerei-1.18#58]
May I ask why this mod was blocked for third-party launchers? I can only assume it was so that CF's download statistics are not messed up. Can this mod be unblocked? Many people don't, or straight up can't use Overwolf's launcher due to privacy concerns, and the fact that it is not available for linux (it only supports WOW). Due to this people have to manually download this mod everytime from the website (which, imo, is pretty meh) and forgo automatic updates for good.

**Comment by Su5eD** [comment]
Hi, I don't know why this was closed without any comment of it being a duplicate, but the topic has already been discussed earlier in #38 (could the issue be pinned to lower the amount of future duplicates?). Unfortunately it looks like the mod is to remain blocked due to financial reasons. Hopefully the mod author reconsiders this choice in the future...

Hope this helped!

**Comment by JoeFoxe** [comment]
I can reconsider this choice if I actually am funded enough to be able to survive myself off working on this. Only way to make this come faster is to help me survive while doing this so I am able to release to all while being able to feed myself and pay for rent
